language: python
python:
- 2.7
- 3.5
- "pypy"
install:
   - make lib
   - pip install -e .
script: python -m thing
sudo: false
addons:
  apt:
    sources:
       - pypy-ppa
    packages:
       - libffi-dev
       - pypy
