language: python
python:
- 2.7
- 3.5
- "pypy"
env:
   - DB=sqlite
   - DB=postgres
services:
   - postgresql
before_install:
# We force an update of the virtualenv
   - |
      if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then
         cat ~/apt-get-update.log
         VPATH=$VIRTUAL_ENV
         deactivate
         virtualenv -p /usr/bin/pypy $VPATH
         source $VPATH/bin/activate
         python --version
      fi
   - psql -c 'create database test;' -U postgres
install:
   - if [ "$DB" = "postgres" ]; then pip install -q psycopg2 ; fi
   - make lib
   - pip install -e .
script: python -m thing
sudo: false
addons:
  apt:
    sources:
       - pypy
    packages:
       - libffi-dev
       - pypy
