language: python
python:
- 2.7
- 3.5
- "pypy"
before_install:
   - # We force an update of the virtualenv
   - |
      if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then
         whereis pypy
         cd ~/virtualenv/pypy/
         virtualenv -p /usr/bin/pypy .
      fi
install:
   - make lib
   - pip install -e .
script: python -m thing
sudo: false
addons:
  apt:
    sources:
       - pypy
    packages:
       - libffi-dev
       - pypy
