language: python
python:
- 2.7
- 3.5
- "pypy"
before_install:
# We force an update of the virtualenv
   - |
      if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then
         VPATH=$VIRTUAL_ENV
         deactivate
         virtualenv -p /usr/bin/pypy $VPATH
         source $VPATH/bin/activate
      fi
install:
   - make lib
   - pip install -e .
script: python -m thing
sudo: false
addons:
  apt:
    sources:
       - pypy
    packages:
       - libffi-dev
       - pypy
